apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
spec:
  selector:
    matchLabels:
      app: orderservice-pod
  replicas: 1
  template:
    metadata:
      labels:
        app: orderservice-pod
    spec:
      containers:
        - name: orderservice-container
          image: abhinavnagarro/orderservice:dev
          ports:
            - containerPort: 80
