apiVersion: v1
kind: Service
metadata:
  name: orderservice
  labels:
    name: orders
spec:
  type: ClusterIP
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: orderservice-pod